   export default {
       "nick": "Mick Carter",
       "role": "Front end dev",
       "skills": [
           "vue"
       ],
       "days": [{
           "name": "Sunday",
           "day": [{
               "name": "7am",
               "on": false
           }, {
               "name": "8am",
               "on": false
           }, {
               "name": "9am",
               "on": false
           }, {
               "name": "10am",
               "on": false
           }, {
               "name": "11am",
               "on": false
           }, {
               "name": "12am",
               "on": false
           }, {
               "name": "1pm",
               "on": false
           }, {
               "name": "2pm",
               "on": false
           }, {
               "name": "3pm",
               "on": false
           }, {
               "name": "4pm",
               "on": false
           }, {
               "name": "5pm",
               "on": false
           }, {
               "name": "6pm",
               "on": false
           }, {
               "name": "7pm",
               "on": false
           }],
           "night": [{
               "name": "8pm",
               "on": false,
               "state": "off"
           }, {
               "name": "9pm",
               "on": false,
               "state": "off"
           }, {
               "name": "10pm",
               "on": false,
               "state": "off"
           }, {
               "name": "11pm",
               "on": false,
               "state": "off"
           }, {
               "name": "12pm",
               "on": false,
               "state": "off"
           }, {
               "name": "1am",
               "on": false,
               "state": "off"
           }, {
               "name": "2am",
               "on": false,
               "state": "off"
           }, {
               "name": "3am",
               "on": false,
               "state": "off"
           }, {
               "name": "4am",
               "on": false,
               "state": "off"
           }, {
               "name": "5am",
               "on": false,
               "state": "off"
           }, {
               "name": "6am",
               "on": false,
               "state": "off"
           }]
       }, {
           "name": "Monday",
           "day": [{
               "name": "7am",
               "on": false,
               "state": "off"
           }, {
               "name": "8am",
               "on": false,
               "state": "off"
           }, {
               "name": "on",
               "on": true,
               "state": "on",
               "label": "9am"
           }, {
               "name": "10am",
               "on": true,
               "state": "on"
           }, {
               "name": "11am",
               "on": true,
               "state": "on"
           }, {
               "name": "12am",
               "on": false,
               "state": "off"
           }, {
               "name": "1pm",
               "on": true,
               "state": "on"
           }, {
               "name": "2pm",
               "on": true,
               "state": "on"
           }, {
               "name": "3pm",
               "on": true,
               "state": "on"
           }, {
               "name": "4pm",
               "on": true,
               "state": "on"
           }, {
               "name": "5pm",
               "on": true,
               "state": "on"
           }, {
               "name": "6pm",
               "on": false,
               "state": "off"
           }, {
               "name": "7pm",
               "on": false,
               "state": "off"
           }],
           "night": [{
               "name": "8pm",
               "on": false,
               "state": "off"
           }, {
               "name": "9pm",
               "on": false,
               "state": "off"
           }, {
               "name": "10pm",
               "on": false,
               "state": "off"
           }, {
               "name": "11pm",
               "on": false,
               "state": "off"
           }, {
               "name": "12pm",
               "on": false,
               "state": "off"
           }, {
               "name": "1am",
               "on": false,
               "state": "off"
           }, {
               "name": "2am",
               "on": false,
               "state": "off"
           }, {
               "name": "3am",
               "on": false,
               "state": "off"
           }, {
               "name": "4am",
               "on": false,
               "state": "off"
           }, {
               "name": "5am",
               "on": false,
               "state": "off"
           }, {
               "name": "6am",
               "on": false,
               "state": "off"
           }]
       }, {
           "name": "Tuesday",
           "day": [{
               "name": "7am",
               "on": false,
               "state": "off"
           }, {
               "name": "8am",
               "on": false,
               "state": "off"
           }, {
               "name": "9am",
               "on": true,
               "state": "on"
           }, {
               "name": "10am",
               "on": true,
               "state": "on"
           }, {
               "name": "11am",
               "on": true,
               "state": "on"
           }, {
               "name": "12am",
               "on": false,
               "state": "off"
           }, {
               "name": "1pm",
               "on": true,
               "state": "on"
           }, {
               "name": "2pm",
               "on": true,
               "state": "on"
           }, {
               "name": "3pm",
               "on": true,
               "state": "on"
           }, {
               "name": "4pm",
               "on": true,
               "state": "on"
           }, {
               "name": "5pm",
               "on": true,
               "state": "on"
           }, {
               "name": "6pm",
               "on": false,
               "state": "off"
           }, {
               "name": "7pm",
               "on": false,
               "state": "off"
           }],
           "night": [{
               "name": "8pm",
               "on": false,
               "state": "off"
           }, {
               "name": "9pm",
               "on": false,
               "state": "off"
           }, {
               "name": "10pm",
               "on": false,
               "state": "off"
           }, {
               "name": "11pm",
               "on": false,
               "state": "off"
           }, {
               "name": "12pm",
               "on": false,
               "state": "off"
           }, {
               "name": "1am",
               "on": false,
               "state": "off"
           }, {
               "name": "2am",
               "on": false,
               "state": "off"
           }, {
               "name": "3am",
               "on": false,
               "state": "off"
           }, {
               "name": "4am",
               "on": false,
               "state": "off"
           }, {
               "name": "5am",
               "on": false,
               "state": "off"
           }, {
               "name": "6am",
               "on": false,
               "state": "off"
           }]
       }, {
           "name": "Wednesday",
           "day": [{
               "name": "7am",
               "on": false,
               "state": "off"
           }, {
               "name": "8am",
               "on": false,
               "state": "off"
           }, {
               "name": "9am",
               "on": true,
               "state": "on"
           }, {
               "name": "10am",
               "on": true,
               "state": "on"
           }, {
               "name": "11am",
               "on": true,
               "state": "on"
           }, {
               "name": "12am",
               "on": false,
               "state": "off"
           }, {
               "name": "1pm",
               "on": true,
               "state": "on"
           }, {
               "name": "2pm",
               "on": true,
               "state": "on"
           }, {
               "name": "3pm",
               "on": true,
               "state": "on"
           }, {
               "name": "4pm",
               "on": true,
               "state": "on"
           }, {
               "name": "5pm",
               "on": true,
               "state": "on"
           }, {
               "name": "6pm",
               "on": false,
               "state": "off"
           }, {
               "name": "7pm",
               "on": false,
               "state": "off"
           }],
           "night": [{
               "name": "8pm",
               "on": false,
               "state": "off"
           }, {
               "name": "9pm",
               "on": false,
               "state": "off"
           }, {
               "name": "10pm",
               "on": false,
               "state": "off"
           }, {
               "name": "11pm",
               "on": false,
               "state": "off"
           }, {
               "name": "12pm",
               "on": false,
               "state": "off"
           }, {
               "name": "1am",
               "on": false,
               "state": "off"
           }, {
               "name": "2am",
               "on": false,
               "state": "off"
           }, {
               "name": "3am",
               "on": false,
               "state": "off"
           }, {
               "name": "4am",
               "on": false,
               "state": "off"
           }, {
               "name": "5am",
               "on": false,
               "state": "off"
           }, {
               "name": "6am",
               "on": false,
               "state": "off"
           }]
       }, {
           "name": "Thursday",
           "day": [{
               "name": "7am",
               "on": false,
               "state": "off"
           }, {
               "name": "8am",
               "on": false,
               "state": "off"
           }, {
               "name": "9am",
               "on": true,
               "state": "on"
           }, {
               "name": "10am",
               "on": true,
               "state": "on"
           }, {
               "name": "11am",
               "on": true,
               "state": "on"
           }, {
               "name": "12am",
               "on": false,
               "state": "off"
           }, {
               "name": "1pm",
               "on": true,
               "state": "on"
           }, {
               "name": "2pm",
               "on": true,
               "state": "on"
           }, {
               "name": "3pm",
               "on": true,
               "state": "on"
           }, {
               "name": "4pm",
               "on": true,
               "state": "on"
           }, {
               "name": "5pm",
               "on": true,
               "state": "on"
           }, {
               "name": "6pm",
               "on": false,
               "state": "off"
           }, {
               "name": "7pm",
               "on": false,
               "state": "off"
           }],
           "night": [{
               "name": "8pm",
               "on": false,
               "state": "off"
           }, {
               "name": "9pm",
               "on": false,
               "state": "off"
           }, {
               "name": "10pm",
               "on": false,
               "state": "off"
           }, {
               "name": "11pm",
               "on": false,
               "state": "off"
           }, {
               "name": "12pm",
               "on": false,
               "state": "off"
           }, {
               "name": "1am",
               "on": false,
               "state": "off"
           }, {
               "name": "2am",
               "on": false,
               "state": "off"
           }, {
               "name": "3am",
               "on": false,
               "state": "off"
           }, {
               "name": "4am",
               "on": false,
               "state": "off"
           }, {
               "name": "5am",
               "on": false,
               "state": "off"
           }, {
               "name": "6am",
               "on": false,
               "state": "off"
           }]
       }, {
           "name": "Friday",
           "day": [{
               "name": "7am",
               "on": false,
               "state": "off"
           }, {
               "name": "8am",
               "on": false,
               "state": "off"
           }, {
               "name": "9am",
               "on": true,
               "state": "on"
           }, {
               "name": "10am",
               "on": true,
               "state": "on"
           }, {
               "name": "11am",
               "on": true,
               "state": "on"
           }, {
               "name": "12am",
               "on": false,
               "state": "off"
           }, {
               "name": "1pm",
               "on": true,
               "state": "on"
           }, {
               "name": "2pm",
               "on": true,
               "state": "on"
           }, {
               "name": "3pm",
               "on": true,
               "state": "on"
           }, {
               "name": "4pm",
               "on": true,
               "state": "on"
           }, {
               "name": "5pm",
               "on": true,
               "state": "on"
           }, {
               "name": "6pm",
               "on": false,
               "state": "off"
           }, {
               "name": "7pm",
               "on": false,
               "state": "off"
           }],
           "night": [{
               "name": "8pm",
               "on": false,
               "state": "off"
           }, {
               "name": "9pm",
               "on": false,
               "state": "off"
           }, {
               "name": "10pm",
               "on": false,
               "state": "off"
           }, {
               "name": "11pm",
               "on": false,
               "state": "off"
           }, {
               "name": "12pm",
               "on": false,
               "state": "off"
           }, {
               "name": "1am",
               "on": false,
               "state": "off"
           }, {
               "name": "2am",
               "on": false,
               "state": "off"
           }, {
               "name": "3am",
               "on": false,
               "state": "off"
           }, {
               "name": "4am",
               "on": false,
               "state": "off"
           }, {
               "name": "5am",
               "on": false,
               "state": "off"
           }, {
               "name": "6am",
               "on": false,
               "state": "off"
           }]
       }, {
           "name": "Saturday",
           "day": [{
               "name": "7am",
               "on": false
           }, {
               "name": "8am",
               "on": false
           }, {
               "name": "9am",
               "on": false
           }, {
               "name": "10am",
               "on": false
           }, {
               "name": "11am",
               "on": false
           }, {
               "name": "12am",
               "on": false
           }, {
               "name": "1pm",
               "on": false
           }, {
               "name": "2pm",
               "on": false
           }, {
               "name": "3pm",
               "on": false
           }, {
               "name": "4pm",
               "on": false
           }, {
               "name": "5pm",
               "on": false
           }, {
               "name": "6pm",
               "on": false
           }, {
               "name": "7pm",
               "on": false
           }],
           "night": [{
               "name": "8pm",
               "on": false,
               "state": "off"
           }, {
               "name": "9pm",
               "on": false,
               "state": "off"
           }, {
               "name": "10pm",
               "on": false,
               "state": "off"
           }, {
               "name": "11pm",
               "on": false,
               "state": "off"
           }, {
               "name": "12pm",
               "on": false,
               "state": "off"
           }, {
               "name": "1am",
               "on": false,
               "state": "off"
           }, {
               "name": "2am",
               "on": false,
               "state": "off"
           }, {
               "name": "3am",
               "on": false,
               "state": "off"
           }, {
               "name": "4am",
               "on": false,
               "state": "off"
           }, {
               "name": "5am",
               "on": false,
               "state": "off"
           }, {
               "name": "6am",
               "on": false,
               "state": "off"
           }]
       }],
       "owner": true,
       "name": "cick.marter@gmail.com",
       "diary": [{
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "colour": "white",
           "date": "2018-01-01T00:00:00.000Z"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "colour": "white",
           "date": "2018-01-02T00:00:00.000Z"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "date": "2018-01-03T00:00:00.000Z",
           "colour": "white"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "colour": "white",
           "date": "2018-01-04T00:00:00.000Z"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "date": "2018-01-05T00:00:00.000Z",
           "colour": "white"
       }, {
           "state": 0,
           "display": "0 hours",
           "off": false,
           "hours": "0 hours",
           "date": "2018-01-06T00:00:00.000Z",
           "colour": "white"
       }, {
           "state": 2,
           "display": "0 hours",
           "colour": "grey",
           "off": true,
           "date": "2018-01-07T00:00:00.000Z"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "date": "2018-01-08T00:00:00.000Z",
           "colour": "white"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "date": "2018-01-09T00:00:00.000Z",
           "colour": "white"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "date": "2018-01-10T00:00:00.000Z",
           "colour": "white"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "colour": "white",
           "date": "2018-01-11T00:00:00.000Z"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "colour": "white",
           "date": "2018-01-12T00:00:00.000Z"
       }, {
           "state": 2,
           "display": "0 hours",
           "colour": "grey",
           "off": true,
           "date": "2018-01-13T00:00:00.000Z"
       }, {
           "state": 2,
           "display": "0 hours",
           "colour": "grey",
           "off": true,
           "date": "2018-01-14T00:00:00.000Z"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "colour": "white",
           "date": "2018-01-15T00:00:00.000Z"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "colour": "white",
           "date": "2018-01-16T00:00:00.000Z"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "colour": "white",
           "date": "2018-01-17T00:00:00.000Z"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "colour": "white",
           "date": "2018-01-18T00:00:00.000Z"
       }, {
           "state": 0,
           "display": "8 hours",
           "off": false,
           "hours": "8 hours",
           "colour": "white",
           "date": "2018-01-19T00:00:00.000Z"
       }, {
           "state": 2,
           "display": "0 hours",
           "colour": "grey",
           "off": true,
           "date": "2018-01-20T00:00:00.000Z"
       }]
   }
